version: 2

updates:
  # Workbench app dependencies
  - package-ecosystem: npm
    directory: /pcf-workbench/workbench-app
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    target-branch: develop
    labels:
      - dependencies
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch

  # GitHub Actions versions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    target-branch: develop
    labels:
      - ci
