blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://learn.microsoft.com/en-us/power-apps/developer/component-framework/overview
    about: Official Microsoft PCF documentation
